# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: C4 website
email: travis@c4ios.com
description: C4 is an open-source creative coding framework that harnesses the power of native iOS programming with a simplified API that gets you working with media right away.
baseurl: "" # the subpath of your site, e.g. /blog
url: "www.c4ios.com" # the base hostname & protocol for your site
twitter_username: c4framework
github_username:  c4framework

# Build settings
markdown: kramdown

highlighter: rouge

sass:
  sass_dir: css
  style:    expanded

exclude:
- README.md

lsi: false

gems: 
  - pygments.rb